:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_1.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_2.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_3.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_4.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_6.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_8.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_9.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_11.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_12.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_13.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_14.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_15.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_23.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_18.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_19.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_20.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_21.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_24.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_25.db" "/data/data/com.hadithbd.banglahadith/databases"
:: adb push "D:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\hb_26.db" "/data/data/com.hadithbd.banglahadith/databases"

adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_1.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_2.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_3.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_4.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_5.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_6.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_7.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_8.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_9.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_10.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_11.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_12.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_13.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_14.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_15.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_16.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_17.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_18.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_19.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_20.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_21.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_22.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_24.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_23.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_25.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_26.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_27.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_28.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_29.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_30.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_31.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_32.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_33.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_39.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_35.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_36.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_37.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_38.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_40.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_41.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_42.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_43.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_44.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_45.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_46.db" "/data/data/com.hadithbd.banglahadith/databases"
adb push "F:\xampp\htdocs\bangla_hadith_android_sqlite_generate_php\ob_47.db" "/data/data/com.hadithbd.banglahadith/databases"